document.write("M Poojitha"+"<br>");
document.write("K Ruchitha"+"<br>");
document.write("Ganesh"+"<br>");
document.write("K Subba Rao"+"<br>");
document.write("Shaik Roshini"+"<br>");
document.write("S.Maheen Noor"+"<br>");
alert("Dont open this website");
alert("Iam Konde Rajini from USA");
document.write("k Shilpa"+"<br>");
document.write("Anwar Basha"+"<br>");
document.getElementById("meghana").innerHTML="Meghana";
console.log("Hi iam from Bangalore.....");
console.log("Jagadheesh Achari");
console.log("we are all from america...");
console.log("From UK");